### ISSUE TITLE
Add instructions on how to start LNX Studio on Linux

### ISSUE THREAD

**Issue by ycollet** [neilcosgrove/LNX_Studio#16]
I wanted to start the LNX Studio tool on Linux (Fedora 23 64 bits with supercollider 3.7.0).
Can you add some instructions on how to set supercollider path a how to start lnx ?

**Comment by neilcosgrove** [comment]
Hi.
There are instructions on the xplat branch. https://github.com/neilcosgrove/LNX_Studio/blob/xplat/README_linux.md

**Comment by ycollet** [comment]
Thanks a lot, it works fine.
Best regards,
YC
