### ISSUE TITLE
LNX Studio live mode and more

### ISSUE THREAD

**Issue by Reaper10** [neilcosgrove/LNX_Studio#18]
LNX Studio need 
session view
![session_view](https://cloud.githubusercontent.com/assets/8137561/17273015/8fc553d4-566c-11e6-97d6-65bf98e4bf99.jpg)

![bts-mixer-clip-launcher](https://cloud.githubusercontent.com/assets/8137561/17273034/18b8f97a-566d-11e6-829b-1a72f63cba7e.png)
https://github.com/openAVproductions/openAV-Luppp
is a good start
edit view
![arrangement_view](https://cloud.githubusercontent.com/assets/8137561/17273069/fe38d1aa-566d-11e6-8b1a-77d799494034.png)
![bitwig-studio-arranger 1](https://cloud.githubusercontent.com/assets/8137561/17273084/d1707816-566e-11e6-94ed-75983cca5dcf.png)

wave editer
![screen-shot-2013-01-28-at-7 09 58-pm 1](https://cloud.githubusercontent.com/assets/8137561/17273098/6c2aa5f2-566f-11e6-947d-94eea34ee143.jpg)

![live-auto-warp 1](https://cloud.githubusercontent.com/assets/8137561/17273112/01ad1b64-5670-11e6-811f-5890b7538e85.jpg)

ability to combine plugin 
![bitwig-studio-arranger](https://cloud.githubusercontent.com/assets/8137561/17273144/fc97e0c2-5670-11e6-9286-05bd3cc536cb.png)

video for idea mining 
https://www.youtube.com/watch?v=NOZP0xuRENY
Your software can be the next live or bitwig

**Comment by andyr0id** [comment]
Thanks for your comments - we've got big plans for LNX and some things you mentioned are part of that. Watch this space!
