### ISSUE TITLE
LNX Studio questions

### ISSUE THREAD

**Issue by Reaper10** [neilcosgrove/LNX_Studio#20]
Can you import and export flac ogg mp3 files? Can you import and export stems of audio?

**Comment by andyr0id** [comment]
Hi,

You can import and use any audio file that SuperCollider supports - it's a huge list, but yes flac ogg and mp3 files should be supported. To import them, copy them to your LNX Sample Cache: `~/music/LNX_Studio Sample Cache`. Then just search for them in the browser and they should turn up in the list. This includes stems.

For now only aiff export is supported, but you can easily convert with afconvert or ffmpeg. We're working on ways to export stems.
