### ISSUE TITLE
runtime error on Linux

### ISSUE THREAD

**Issue by davephillips** [neilcosgrove/LNX_Studio#21]
$ ./LNX_Studio 
init_OSC
compiling class library...
initPassOne started
    NumPrimitives = 712
initPassOne done
    compiling dir: '/usr/local/share/SuperCollider/SCClassLibrary/'
    excluding dir: '/usr/local/share/SuperCollider/SCClassLibrary//deprecated'
    compiling dir: '/usr/local/share/SuperCollider/Extensions/SC3plugins/'
    excluding file: '/usr/local/share/SuperCollider/Extensions/SC3plugins//SkUGens/FM7.sc'
    compiling dir: '/home/dlphilp/src/LNX_Studio/SCClassLibrary/'
    pass 1 done
ERROR: Class extension for nonexistent class 'Matrix'
     In file:'/usr/local/share/SuperCollider/Extensions/SC3plugins//ATK/Classes/extMatrix.sc'
ERROR: Class extension for nonexistent class 'FM7'
     In file:'/home/dlphilp/src/LNX_Studio/SCClassLibrary//LNX_Studio Library/10. by others/UGenCategories.sc'
ERROR: Class extension for nonexistent class 'MainMenu'
     In file:'/home/dlphilp/src/LNX_Studio/SCClassLibrary//LNX_Studio Library/9. Start Up/SystemOverwrites/Menu.sc'
    numentries = 1513532 / 35169282 = 0.043
    9173 method selectors, 3834 classes
    method table size 30178392 bytes, big table size 281354256
    Number of Symbols 21713
    Byte Code Size 1145138
    compiled 734 files in 1.58 seconds

Info: 30 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done
ERROR: Primitive '_QImage_NewPath' failed.
Failed.
RECEIVER:
Instance of Image {    (0x2667108, gc=BC, fmt=00, flg=00, set=03)
  instance variables [5]
    dataptr : nil
    finalizer : nil
    name : nil
    url : nil
    scalesWhenResized : false
}
CALL STACK:
    MethodError:reportError   0x26607e8
        arg this = <instance of PrimitiveFailedError>
        var s = "ERROR: Primitive '_QImage_Ne..."
    Nil:handleError   0x2660978
        arg this = nil
        arg error = <instance of PrimitiveFailedError>
    Thread:handleError   0x2660b08
        arg this = <instance of Thread>
        arg error = <instance of PrimitiveFailedError>
    Object:throw   0x2660c98
        arg this = <instance of PrimitiveFailedError>
    Object:primitiveFailed   0x2667318
        arg this = <instance of Image>
    Meta_MVC_ImageView:initClass   0x26636c8
        arg this = <instance of Meta_MVC_ImageView>
    Meta_Class:initClassTree   0x2665848
        arg this = <instance of Meta_Class>
        arg aClass = <instance of Meta_MVC_ImageView>
        var implementsInitClass = nil
    ArrayedCollection:do   0x26727d8
        arg this = [_46]
        arg function = <instance of Function>
        var i = 38
    Meta_Class:initClassTree   0x28a4a18
        arg this = <instance of Meta_Class>
        arg aClass = <instance of Meta_MVC_View>
        var implementsInitClass = nil
    ArrayedCollection:do   0x2963af8
        arg this = [_440]
        arg function = <instance of Function>
        var i = 253
    Meta_Class:initClassTree   0x2962cf8
        arg this = <instance of Meta_Class>
        arg aClass = <instance of Meta_Object>
        var implementsInitClass = nil
    Process:startup   0x2961d78
        arg this = <instance of Main>
        var time = 1.600403008
    Main:startup   0x2960788
        arg this = <instance of Main>
        var didWarnOverwrite = false

**Comment by andyr0id** [comment]
Hi Dave,

Can you check the contents of `/home/dlphilp/.local/share/LNX_Studio/` and let know know what's in there?

Cheers,
Andy

**Comment by davephillips** [comment]
Hi Andy,

Here you go:

[dlphilp@The6300 LNX_Studio]$ ls -l
total 568
drwxrwxr-x 19 dlphilp dlphilp   4096 Apr 13 17:23 default library
-rw-rw-r--  1 dlphilp dlphilp 245433 Apr 19 11:57 demo song
lrwxrwxrwx  1 dlphilp dlphilp     34 Apr 26 06:26 downloaded-quarks -> ../SuperCollider/downloaded-quarks
drwxrwxr-x  3 dlphilp dlphilp   4096 Apr 26 06:23 downloaded-quarks.prev
drwxrwxr-x  2 dlphilp dlphilp   4096 Sep 30 08:36 fontImages
-rw-rw-r--  1 dlphilp dlphilp 112698 Apr 13 17:23 lnx.jpg
-rw-rw-r--  1 dlphilp dlphilp      4 Apr 26 08:57 lnx_version
-rw-rw-r--  1 dlphilp dlphilp  26312 Apr 13 17:23 screen shot 1.3.jpg
-rw-rw-r--  1 dlphilp dlphilp 169156 Sep 30 08:36 screen shot 1.3.png
drwxrwxr-x  3 dlphilp dlphilp   4096 Apr 19 11:57 sounds

**Comment by andyr0id** [comment]
I just pushed a commit that should fix it - let me know if it works for you!

**Comment by davephillips** [comment]
Hi Andy,

Looking and sounding good now, thanks for the help. :) The demo song played perfectly, ditto for the Clair de Lune SC Code example. However, some errors were reported that may be significant, here's the report :

[dlphilp@The6300 LNX_Studio]$ ./LNX_Studio 
init_OSC
compiling class library...
initPassOne started
    NumPrimitives = 712
initPassOne done
    compiling dir: '/usr/local/share/SuperCollider/SCClassLibrary/'
    excluding dir: '/usr/local/share/SuperCollider/SCClassLibrary//deprecated'
    compiling dir: '/usr/local/share/SuperCollider/Extensions/SC3plugins/'
    excluding file: '/usr/local/share/SuperCollider/Extensions/SC3plugins//SkUGens/FM7.sc'
    compiling dir: '/home/dlphilp/src/LNX_Studio/SCClassLibrary/'
    pass 1 done
ERROR: Class extension for nonexistent class 'Matrix'
     In file:'/usr/local/share/SuperCollider/Extensions/SC3plugins//ATK/Classes/extMatrix.sc'
ERROR: Class extension for nonexistent class 'FM7'
     In file:'/home/dlphilp/src/LNX_Studio/SCClassLibrary//LNX_Studio Library/10. by others/UGenCategories.sc'
ERROR: Class extension for nonexistent class 'MainMenu'
     In file:'/home/dlphilp/src/LNX_Studio/SCClassLibrary//LNX_Studio Library/9. Start Up/SystemOverwrites/Menu.sc'
    numentries = 1513535 / 35180784 = 0.043
    9176 method selectors, 3834 classes
    method table size 30178416 bytes, big table size 281446272
    Number of Symbols 21717
    Byte Code Size 1145660
    compiled 734 files in 1.55 seconds

Info: 30 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
Class tree inited in 0.1 seconds
Cleaning up temp synthdefs...
RESULT = 0
WARNING:
MIDIClient-init requested 16 inport(s) and 16 outport(s),
but found only 7 inport(s) and 5 outport(s).
Some expected MIDI devices may not be available.
MIDI Sources:
    MIDIEndPoint("System", "Timer")
    MIDIEndPoint("System", "Announce")
    MIDIEndPoint("Midi Through", "Midi Through Port-0")
    MIDIEndPoint("Virtual Raw MIDI 2-0", "VirMIDI 2-0")
    MIDIEndPoint("Virtual Raw MIDI 2-1", "VirMIDI 2-1")
    MIDIEndPoint("Virtual Raw MIDI 2-2", "VirMIDI 2-2")
    MIDIEndPoint("Virtual Raw MIDI 2-3", "VirMIDI 2-3")
    MIDIEndPoint("SuperCollider", "out0")
    MIDIEndPoint("SuperCollider", "out1")
    MIDIEndPoint("SuperCollider", "out2")
    MIDIEndPoint("SuperCollider", "out3")
    MIDIEndPoint("SuperCollider", "out4")
    MIDIEndPoint("SuperCollider", "out5")
    MIDIEndPoint("SuperCollider", "out6")
    MIDIEndPoint("SuperCollider", "out7")
    MIDIEndPoint("SuperCollider", "out8")
    MIDIEndPoint("SuperCollider", "out9")
    MIDIEndPoint("SuperCollider", "out10")
    MIDIEndPoint("SuperCollider", "out11")
    MIDIEndPoint("SuperCollider", "out12")
    MIDIEndPoint("SuperCollider", "out13")
    MIDIEndPoint("SuperCollider", "out14")
    MIDIEndPoint("SuperCollider", "out15")
MIDI Destinations:
    MIDIEndPoint("Midi Through", "Midi Through Port-0")
    MIDIEndPoint("Virtual Raw MIDI 2-0", "VirMIDI 2-0")
    MIDIEndPoint("Virtual Raw MIDI 2-1", "VirMIDI 2-1")
    MIDIEndPoint("Virtual Raw MIDI 2-2", "VirMIDI 2-2")
    MIDIEndPoint("Virtual Raw MIDI 2-3", "VirMIDI 2-3")
    MIDIEndPoint("SuperCollider", "in0")
    MIDIEndPoint("SuperCollider", "in1")
    MIDIEndPoint("SuperCollider", "in2")
    MIDIEndPoint("SuperCollider", "in3")
    MIDIEndPoint("SuperCollider", "in4")
    MIDIEndPoint("SuperCollider", "in5")
    MIDIEndPoint("SuperCollider", "in6")
    MIDIEndPoint("SuperCollider", "in7")
    MIDIEndPoint("SuperCollider", "in8")
    MIDIEndPoint("SuperCollider", "in9")
    MIDIEndPoint("SuperCollider", "in10")
    MIDIEndPoint("SuperCollider", "in11")
    MIDIEndPoint("SuperCollider", "in12")
    MIDIEndPoint("SuperCollider", "in13")
    MIDIEndPoint("SuperCollider", "in14")
    MIDIEndPoint("SuperCollider", "in15")
Warning: MIDIEndPoint("SuperCollider", "in11") failed to init
Warning: MIDIEndPoint("SuperCollider", "in12") failed to init
Warning: MIDIEndPoint("SuperCollider", "in13") failed to init
Warning: MIDIEndPoint("SuperCollider", "in14") failed to init
Warning: MIDIEndPoint("SuperCollider", "in15") failed to init
Warning: MIDIEndPoint("SuperCollider", "out9") failed to init
Warning: MIDIEndPoint("SuperCollider", "out10") failed to init
Warning: MIDIEndPoint("SuperCollider", "out11") failed to init
Warning: MIDIEndPoint("SuperCollider", "out12") failed to init
Warning: MIDIEndPoint("SuperCollider", "out13") failed to init
Warning: MIDIEndPoint("SuperCollider", "out14") failed to init
Warning: MIDIEndPoint("SuperCollider", "out15") failed to init
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
WARNING: Extension in '/usr/local/share/SuperCollider/SCClassLibrary//Platform/linux/extMIDIOut.sc' overwrites Meta_MIDIClient:externalSources in main class library.
WARNING: Extension in '/usr/local/share/SuperCollider/SCClassLibrary//Platform/linux/extMIDIOut.sc' overwrites Meta_MIDIClient:externalDestinations in main class library.
WARNING: Extension in '/usr/local/share/SuperCollider/SCClassLibrary//Platform/linux/extMIDIOut.sc' overwrites Meta_MIDIIn:connectAll in main class library.
WARNING: Extension in '/usr/local/share/SuperCollider/SCClassLibrary//backwards_compatibility/extMethods.sc' overwrites Env:asControlInput in main class library.
WARNING: Extension in '/usr/local/share/SuperCollider/SCClassLibrary//backwards_compatibility/extMethods.sc' overwrites Env:asOSCArgEmbeddedArray in main class library.
WARNING: Extension in '/usr/local/share/SuperCollider/SCClassLibrary//backwards_compatibility/extMethods.sc' overwrites Object:asOSCArgEmbeddedArray in main class library.
WARNING: Extension in '/usr/local/share/SuperCollider/SCClassLibrary//backwards_compatibility/extMethods.sc' overwrites Object:asOSCArgArray in main class library.
WARNING: Extension in '/usr/local/share/SuperCollider/SCClassLibrary//backwards_compatibility/extMethods.sc' overwrites Object:asOSCArgBundle in main class library.
WARNING: Extension in '/usr/local/share/SuperCollider/SCClassLibrary//backwards_compatibility/extMethods.sc' overwrites Object:asStringff in main class library.
WARNING: Extension in '/usr/local/share/SuperCollider/SCClassLibrary//backwards_compatibility/extMethods.sc' overwrites Object:postff in main class library.
WARNING: Extension in '/usr/local/share/SuperCollider/SCClassLibrary//backwards_compatibility/extMethods.sc' overwrites Nil:asOSCArgArray in main class library.
WARNING: Extension in '/usr/local/share/SuperCollider/SCClassLibrary//backwards_compatibility/extMethods.sc' overwrites Ref:asOSCArgEmbeddedArray in main class library.
WARNING: Extension in '/usr/local/share/SuperCollider/SCClassLibrary//backwards_compatibility/extMethods.sc' overwrites AbstractFunction:eq in main class library.
WARNING: Extension in '/usr/local/share/SuperCollider/SCClassLibrary//backwards_compatibility/extMethods.sc' overwrites AbstractFunction:ne in main class library.
Intentional overwrites must be put in a 'SystemOverwrites' subfolder.

**\* Welcome to SuperCollider 3.8dev. **\* For help type ctrl-c ctrl-h (Emacs) or :SChelp (vim) or ctrl-U (sced/gedit).
Bootng Server: 1
booting 57110
Found 40 LADSPA plugins
JackDriver: client name is 'SuperCollider'
SC_AudioDriver: sample rate = 48000.000000, driver's block size = 128
JackDriver: connected  system:capture_1 to SuperCollider:in_1
JackDriver: connected  system:capture_2 to SuperCollider:in_2
JackDriver: connected  SuperCollider:out_1 to system:playback_1
JackDriver: connected  SuperCollider:out_2 to system:playback_2
SuperCollider 3 server ready.
JackDriver: max output latency 5.3 ms
ERROR: Message 'front' not understood.
RECEIVER:
   nil
ARGS:
CALL STACK:
    DoesNotUnderstandError:reportError   0x5e67ee8
        arg this = <instance of DoesNotUnderstandError>
        var s = "ERROR: Message 'front' not u..."
    < closed FunctionDef >   0x5e68128
        arg error = <instance of DoesNotUnderstandError>
    Integer:forBy   0x5af2998
        arg this = 0
        arg endval = 0
        arg stepval = 2
        arg function = <instance of Function>
        var i = 0
        var j = 0
    SequenceableCollection:pairsDo   0x5e6d378
        arg this = [*2]
        arg function = <instance of Function>
    Scheduler:seconds_   0x5e6d428
        arg this = <instance of Scheduler>
        arg newSeconds = 4.82316209
    Meta_AppClock:tick   0x5e6d758
        arg this = <instance of Meta_AppClock>
        var saveClock = <instance of Meta_SystemClock>
    Process:tick   0x5e6d808
        arg this = <instance of Main>
Receiving notification messages from server localhost
Shared memory server interface initialized

**Comment by andyr0id** [comment]
great, thanks!
