### ISSUE TITLE
more built in fx in mixer

### ISSUE THREAD

**Issue by Reaper10** [neilcosgrove/LNX_Studio#23]
more built in fx in mixer like:
1. compressor
2. limiter
3. gate
4. tape saturation

**Comment by andyr0id** [comment]
Hi, 

Thanks for your suggestions. 

We already have compressor and limiter FX. 

One of the features of LNX is the ability to create your own synths and FX with SC Code. If you'd like to make a gate/tape saturation effect, send  it to lnxstudioapp@gmail.com and we'll add it to the default library. 

Cheers, 
Andy
