### ISSUE TITLE
Problem in Linux version: "sclang: invalid option -a"

### ISSUE THREAD

**Issue by lrodero** [neilcosgrove/LNX_Studio#8]
I am using Linux Ubuntu 15.04, with SuperCollider version 3.6.6 (the one installed by Ubuntu packages). In the `xplat` branch, After following the installation [instructions for Linux](https://github.com/neilcosgrove/LNX_Studio/blob/xplat/README_linux.md), I try to run the `LNX_Studio` script. But I get this message:

```
$ ./LNX_Studio 
sclang: invalid option -a
```

If I remove that `-a` option from the startup script then it seems SuperCollider cannot compile the LNX_Libraries with the library paths it has hardcoded:

```
$ ./LNX_Studio 
init_OSC
empty
compiling class library...
    NumPrimitives = 679
    compiling dir: '/usr/share/SuperCollider/SCClassLibrary'
    excluding dir: '/usr/share/SuperCollider/SCClassLibrary/deprecated'
    compiling dir: '/usr/share/SuperCollider/Extensions'
    compiling dir: '/home/lrodero/.local/share/SuperCollider/Extensions'
    excluding file: '/home/lrodero/.local/share/SuperCollider/Extensions/SC3plugins/SkUGens/FM7.sc'
    compiling dir: '/home/lrodero/Software/LNX_Studio/SCClassLibrary/'
    excluding dir: '/home/lrodero/Software/LNX_Studio/SCClassLibrary//LNX_Studio Library/10. by others/AppKitViews'
    pass 1 done
ERROR: Variable 'mouseDownAction' not defined.
  in file '/home/lrodero/Software/LNX_Studio/SCClassLibrary//LNX_Studio Library/7. MVC/MVC_NumberBox.sc'
  line 325 char 17:

        mouseDownAction.value(this, x, y, modifiers, buttonNumber, clickCount);

    }
-----------------------------------
(... and many errors more )
```

Adding SuperCollider paths manually to `sclang_conf_lnx.yaml` only makes `sclang` complain it is finding many classes defined twice. So I have to leave it as this:

```
includePaths:
    - /home/lrodero/Software/LNX_Studio/SCClassLibrary/
excludePaths:
    - /usr/share/SuperCollider/SCClassLibrary/deprecated/
    - /home/lrodero/.local/share/SuperCollider/Extensions/SC3plugins/SkUGens/FM7.sc
    - /home/lrodero/Software/LNX_Studio/SCClassLibrary/LNX_Studio Library/10. by others/AppKitViews
postInlineWarnings: false
```

It seems also I'm not the only one with this problem, see [this message](https://linuxmusicians.com/viewtopic.php?f=24&t=15616#p70445) at linuxmusicians forum

> Not much luck running it here, I get "sclang: invalid option -a" (...)

Thanks in advance for your help!

**Comment by lrodero** [comment]
The problem seems to be with `sclang` itself... Now, I see the `-a` flag is related with libs include paths. That must be why I can't get it right. If I start LNX_Studio without that flag `sclang` complains it can't compile some classes in `/home/lrodero/Software/LNX_Studio/SCClassLibrary/`, the error messages seem to show there is some lib missing... still I can't guess which one it is (default hardcoded paths seem to import the same libraries that I'd put in `sclang_conf_lnx.yaml`). I'll keep working on it. But really it seems is not a LNX_Studio issue.

**Comment by andyr0id** [comment]
Thanks @lrodero.

Yes it seems you need to have the -a option or the classpaths aren't set correctly. I'll look into what version -a was added to sclang and update README_linux.
